"""
Step 5 - Scraping a Dynamic Website with Selenium
=================================================

Goal: Extract data from a website whose content is rendered by JavaScript.

Why do we need Selenium?
  Try opening https://quotes.toscrape.com/js/ with requests + BeautifulSoup
  and the result is EMPTY, because the quotes are generated by JavaScript in
  the browser. Selenium controls a real browser, so the JavaScript runs too.

Selenium can be used to: click buttons, scroll, log in, and extract data
from dynamic websites.

DRIVER NOTE:
  The driver is downloaded AUTOMATICALLY by Selenium Manager (built into
  Selenium >= 4.6), so there is NO need to install ChromeDriver manually.
  Just make sure Chrome/Chromium is installed (see README).

  By default the browser is VISIBLE (headless=False) so we can watch the
  automation during live coding. Set headless=True if you want it to run
  without opening a browser window.

Run:
    uv run python steps/05_selenium_dinamis.py
"""

from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By

URL = "https://quotes.toscrape.com/js/"


def build_driver(headless: bool = False) -> webdriver.Chrome:
    options = Options()
    if headless:
        # run without a browser window (optional)
        options.add_argument("--headless=new")
    options.add_argument("--window-size=1920,1080")
    # Selenium Manager automatically sets up a matching driver
    return webdriver.Chrome(options=options)


def main() -> None:
    driver = build_driver()
    try:
        driver.get(URL)

        # Get all quote elements on the page (generated by JavaScript)
        quotes = driver.find_elements(By.CLASS_NAME, "quote")
        print(f"=== Successfully fetched {len(quotes)} quotes from a dynamic website ===")

        for q in quotes[:5]:
            text = q.find_element(By.CLASS_NAME, "text").text
            author = q.find_element(By.CLASS_NAME, "author").text
            print(f"- {text}  -- {author}")
    finally:
        driver.quit()  # always close the browser to avoid wasting memory


if __name__ == "__main__":
    main()
